### ISSUE TITLE
are the images in this dataset from the COCO dataset

### ISSUE THREAD

**Issue by khanhha** [Fang-Haoshu/Halpe-FullBody#1]
Hello, 
Thanks you for creating a wonderful dataset.
- I would like to ask if the images from the Halpe-Fullbody dataset are the ones from the COCO2017 dataset?
- What is the difference between the Coco Full Body keypoint dataset and Halpe-FullBody dataset? Do they use the same COCO images or not?
Thanks

**Comment by Fang-Haoshu** [comment]
Hi, the images of Halpe are from HICO-DET dataset.
