### ISSUE TITLE
为什么halpe里面有多个人，halpe_train_v1.json标注文件才只给了一个人的标注？是我搞错了吗？还是就是一张图片只能一个注释？

### ISSUE THREAD

**Issue by LMR2018** [Fang-Haoshu/Halpe-FullBody#13]
为什么halpe里面有多个人，halpe_train_v1.json标注文件才只给了一个人的标注？是我搞错了吗？还是就是一张图片只能一个注释？

**Comment by Fang-Haoshu** [comment]
一张照片只有一个标注，https://github.com/Fang-Haoshu/Halpe-FullBody/issues/5

**Comment by mhzhou2021** [comment]
HICO_train2015_00037881.jpg标记了3个人脸，还存在少量的同一人脸重复标记的情况
