### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'halpe_train_v1.json'

### ISSUE THREAD

**Issue by Murmelmaus** [Fang-Haoshu/Halpe-FullBody#2]
Hello there, 
I'm trying to execute the vis.py, but halpe_train_v1.json is missing. Where do I get this file from?
Thanks in advanse!
Adriana

**Comment by Fang-Haoshu** [comment]
Hi, you can find it here https://github.com/Fang-Haoshu/Halpe-FullBody#download

**Comment by Murmelmaus** [comment]
Thank you very much! I overlooked that. ;)
