### ISSUE TITLE
Only single person in one picture>

### ISSUE THREAD

**Issue by www516717402** [Fang-Haoshu/Halpe-FullBody#3]
Thank you for share great project. Question as titles.

**Comment by jamesay23** [comment]
i find the same problem.

**Comment by hongyaohongyao** [comment]
Alphapose implements multi person with this net. Is that what you mean?

**Comment by Fang-Haoshu** [comment]
Hi, we annotate one person in one picture because the HOI label are only labeled for one person in HICO-DET.
Thus, our data is suitable for detection based multi-person pose estimation.
