### ISSUE TITLE
The dataset cannot be downloaded

### ISSUE THREAD

**Issue by APeiZou** [Fang-Haoshu/Halpe-FullBody#9]
@Fang-Haoshu ， Hello ，  The dataset cannot be downloaded。
![企业微信截图_16602056654045](https://user-images.githubusercontent.com/49524647/184091625-7f2e13c7-3601-4d3b-bdf5-e5475334c320.png)

**Comment by Fang-Haoshu** [comment]
as said, it is the problem of the google drive
